using System.Windows;
using System.Windows.Controls;
using Bws.Core;
using Bws.Core.Planning;

namespace Bws.Gui.ViewModels;

/// <summary>
/// The data the sheet's samples are drawn over - the half of the catalogue that is neither a style
/// nor a view, but what a style or a view has to HOLD to be looked at.
///
/// <b>Data, not text the window says</b>, the argument <see cref="Short"/> makes one level up: a
/// template drawn over nothing is a blank cell, and a blank cell is a claim about the product. So
/// each keyed template of the theme files is drawn here over a specimen of the thing it is for -
/// a suggestion row over a suggestion, a cell over a row, a plan line over a plan line.
///
/// <b>Synthetic, and that is a rule rather than a shortcut.</b> Backlog 45 records that the test
/// fixtures carry four real security descriptors from the owner's machine. Nothing here may - this
/// file ships in the product. Every path, account, descriptor and description below is made up or
/// generated, and the long ones are generated by repetition rather than copied from anything.
///
/// <b>A small machine rather than one entry</b>, because a list with one row shows no separator,
/// no alternation and no scroll, and a view "with data" over one entry is a view with almost none.
/// Eight entries, in the shapes `docs/05` lists as the ones a real machine has: a stopped service
/// with a trigger, one disabled and still running, one whose file is gone, a per-user template,
/// two kinds of driver, and one with the longest of everything.
///
/// <b>Built by a factory with parameters, not written out field by field</b> - the lesson Rows.cs
/// in the tests learned on 2026-08-05, and the reason this file stays under the length ceiling
/// with eight entries of twenty five fields each.
/// </summary>
public static partial class Catalogue
{
    /// <summary>
    /// The template CatalogueWindow.xaml draws each row of the sheet with - the key that says a
    /// dictionary IS the sheet's own theme file, whatever it is called and wherever it was read.
    /// </summary>
    private const string SheetRowTemplate = "CatalogueEntry";

    /// <summary>
    /// A name past any column, made rather than copied: eighty characters with no space in
    /// them, which is the shape that cannot wrap and has to be cut.
    /// </summary>
    private static readonly string LongName = new string('W', 40) + new string('i', 40);

    /// <summary>
    /// The longest text a listing carries. 1 251 characters was the longest description measured
    /// on this project's machine on 2026-08-13 - MemoryBudgetTests records it - and this is a
    /// sentence repeated until it is longer than that, rather than the description itself.
    /// </summary>
    private static readonly string LongDescription = string.Concat(
        Enumerable.Repeat("Keeps something on this machine working, and says so at length. ", 20));

    /// <summary>The eight entries the sheet's views and cells are drawn over.</summary>
    internal static IReadOnlyList<ScmEntry> Specimens() =>
    [
        Specimen("Spooler", "Print Spooler", EntryType.OwnProcess, StartType.Automatic, EntryStatus.Running, "LocalSystem"),
        Specimen("wuauserv", "Windows Update", EntryType.SharedProcess, StartType.Manual, EntryStatus.Stopped, "LocalSystem") with
        {
            Triggers = Reading<IReadOnlyList<ServiceTrigger>>.Present([new ServiceTrigger(TriggerKind.IpAddress, Core.TriggerAction.Start)])
        },
        Specimen("Fax", "Fax", EntryType.OwnProcess, StartType.Disabled, EntryStatus.Running, @"NT AUTHORITY\NetworkService"),
        Specimen("Ghost", "A service whose file is gone", EntryType.OwnProcess, StartType.Manual, EntryStatus.Stopped, @"NT AUTHORITY\LocalService") with
        {
            BinaryOnDisk = Reading<bool>.Present(false)
        },
        Specimen("disk", "Disk Driver", EntryType.KernelDriver, StartType.Boot, EntryStatus.Running, account: null),
        Specimen("NTFS", "NTFS", EntryType.FileSystemDriver, StartType.Boot, EntryStatus.Running, account: null),
        Specimen("npf", "A driver set to start and not running", EntryType.KernelDriver, StartType.Automatic, EntryStatus.Stopped, account: null),
        Specimen(LongName, LongName + " display name", EntryType.OwnProcess, StartType.Automatic, EntryStatus.StopPending, "LocalSystem") with
        {
            Description = Reading<string>.Present(LongDescription),
            RequiredPrivileges = Reading<IReadOnlyList<string>>.Present(
                [.. Enumerable.Range(1, 28).Select(n => "SeSamplePrivilege" + n.ToString(System.Globalization.CultureInfo.InvariantCulture))])
        }
    ];

    /// <summary>The entry that has the most of everything - name, description, privileges.</summary>
    internal static ScmEntry LongestSpecimen() => Specimens()[^1];

    /// <summary>
    /// One entry with every field carrying something, because an entry of empty readings would draw
    /// the shape of the record and not what a real listing holds.
    ///
    /// A driver has no account, no process and no trigger - the manager reads none of those for
    /// one - so a null account is what makes an entry a driver-shaped entry here.
    /// </summary>
    private static ScmEntry Specimen(string name, string displayName, EntryType type, StartType start, EntryStatus status, string? account)
    {
        var running = status is EntryStatus.Running or EntryStatus.StopPending or EntryStatus.StartPending;
        var driver = account is null;

        return new ScmEntry
        {
            ServiceName = name,
            DisplayName = displayName,
            Description = Reading<string>.Present(displayName + " keeps something on this machine working."),
            EntryType = type,
            PerUserRole = PerUserRole.None,
            Status = status,
            ProcessId = running && !driver ? Reading<int>.Present(4812) : Reading<int>.Absent(),
            AcceptsStop = running && !driver ? Reading<bool>.Present(true) : Reading<bool>.Absent(),
            StartType = Reading<StartType>.Present(start),
            DelayedAuto = Reading<bool>.Present(false),
            Account = driver ? Reading<string>.Absent() : Reading<string>.Present(account!),
            DependsOn = Reading<IReadOnlyList<string>>.Present(["RPCSS"]),
            RequiredBy = Reading<IReadOnlyList<string>>.NotRead(),
            Triggers = Reading<IReadOnlyList<ServiceTrigger>>.Absent(),
            BinaryPath = Reading<string>.Present(driver
                ? @"\SystemRoot\System32\drivers\" + name + ".sys"
                : @"C:\Windows\System32\svchost.exe -k netsvcs -p"),
            BinaryFile = Reading<string>.Present(driver
                ? @"C:\Windows\System32\drivers\" + name + ".sys"
                : @"C:\Windows\System32\svchost.exe"),
            BinaryOnDisk = Reading<bool>.Present(true),
            Signature = Reading<BinarySignature>.NotRead(),
            FileVersion = Reading<string>.NotRead(),
            BinaryHash = Reading<string>.NotRead(),
            RequiredPrivileges = driver ? Reading<IReadOnlyList<string>>.Absent() : Reading<IReadOnlyList<string>>.Present(["SeChangeNotifyPrivilege"]),
            SidType = driver ? Reading<ServiceSidType>.Absent() : Reading<ServiceSidType>.Present(ServiceSidType.Unrestricted),

            // The descriptor Microsoft's own documentation uses as its example of the shape - a
            // shape, not a machine's.
            SecurityDescriptor = driver ? Reading<string>.Absent() : Reading<string>.Present("O:SYG:SYD:(A;;CCLCSWLOCRRC;;;AU)(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;BA)"),
            ErrorControl = Reading<ErrorControl>.Present(ErrorControl.Normal),
            LoadOrderGroup = driver ? Reading<string>.Present("SCSI miniport") : Reading<string>.Absent(),
            Memory = Reading<ProcessMemory>.NotRead()
        };
    }

    /// <summary>
    /// What each keyed template is drawn over - the ordinary specimen and the extreme one - or
    /// null for a template this file has never heard of, which the guard turns red.
    ///
    /// <b>By key, deliberately, where the styles go by type.</b> A style names its target type
    /// and a factory per type survives a rebuild. A template names nothing - its data is whatever
    /// the markup binds to - so the only honest table is one that says, per template, what shape
    /// it draws. A new template is a new row here, and a missing row is a red build rather than a
    /// blank cell.
    /// </summary>
    private static (object Normal, object Extreme)? TemplateSpecimens(string key)
    {
        var entries = Specimens();
        var ordinary = EntryRow.Of(entries[0]);
        var longest = EntryRow.Of(LongestSpecimen());

        return key switch
        {
            "SuggestionRow" => (
                new Suggestion("start:", "whether it starts by itself, and how", 0..0, "start:"),
                // The extreme is a QUESTION on purpose: its sentence leads, so the shared lead column
                // is as wide as two hundred characters of it - the worst case for the row, and the
                // other of the two orders the template can take.
                new Suggestion(LongName[..40] + ":", LongDescription[..200], 0..0, LongName[..40] + ":", IsQuestion: true)),

            "FilterGroupTemplate" => (
                new FilterGroup("gui.filter.group.state", Chips("status:running", "status", ("gui.filter.running", "running"), ("gui.filter.stopped", "stopped"), ("gui.filter.paused", "paused"))),
                new FilterGroup("gui.filter.group.start", Chips("start:automatic,manual", "start",
                    ("gui.filter.boot", "boot"), ("gui.filter.system", "system"), ("gui.filter.automatic", "automatic"), ("gui.filter.manual", "manual"),
                    ("gui.filter.disabled", "disabled"), ("gui.filter.delayed", "delayed"), ("gui.filter.running", "running"), ("gui.filter.stopped", "stopped")))),

            "NameCell" => (ordinary, longest),
            "StatusCell" => (ordinary, longest),
            "StartTypeCell" => (ordinary, EntryRow.Of(entries[3])),
            // The ordinary row says No - the extreme is the driver set to start that is not
            // running, which is the one shape that lights the mark.
            "AgainstStartTypeCell" => (ordinary, EntryRow.Of(entries[6])),

            "TrimmedButtonLabel" => ("Stop Print Spooler", "Stop " + LongName + " display name"),
            "PlanLineTemplate" => (
                new PlanLine(new NamedSentence("1. stop ", "Spooler", " (asked for)"), asked: true),
                new PlanLine(new NamedSentence("2. stop ", LongName + " display name", ", which came along"), asked: false)),
            "PlanSentenceTemplate" => ("Stopping this will stop the two entries that depend on it as well.", LongDescription),
            "PlanFailureTemplate" => (new PlanFailure("Windows refused to stop it: access is denied (5).", offer: null), new PlanFailure(LongDescription, offer: null)),

            // The extreme carries the offer, because the button under a long sentence is the one
            // shape of this template that can go wrong - it has to stay under its own sentence.
            "PlanWarningTemplate" => (
                PlanWarningLine.Of([new PlanWarning(PlanWarningKind.ReturnsAfterReboot, "Spooler", [])], offering: false)[0],
                PlanWarningLine.Of([new PlanWarning(PlanWarningKind.KeepsRunning, LongName, [])], offering: true)[0]),
            "PlanCommandTemplate" => ("bws stop Spooler --dry-run", "bws stop " + LongName + " --dependents --timeout 90 --json --timing --follow-network"),

            _ => null
        };
    }

    /// <summary>A row of chips lit by a query, the way the filter row lights them.</summary>
    private static IReadOnlyList<FilterChip> Chips(string query, string field, params (string Key, string Value)[] members) =>
        [.. members.Select(member => new FilterChip(member.Key, field, member.Value, negated: false, () => query, _ => { }))];

    /// <summary>
    /// The keyed templates of the theme files, each drawn over its specimen - one group per file,
    /// beside the file's styles.
    ///
    /// <b>A template is a component as much as a style is.</b> The row under the search box IS
    /// SuggestionRow, a filter group IS FilterGroupTemplate, and until 2026-09-16 the sheet did not
    /// know either existed, because it walked the dictionaries for Style and nothing else.
    ///
    /// <b>The sheet's own file is skipped by what it DECLARES, not by its name.</b> Catalogue.xaml's
    /// four templates are the sheet itself - a sheet drawing its own row template inside its own
    /// row template is a mirror, not a catalogue. The file is known by the row template it holds,
    /// because in the test host every dictionary is read from a stream and has no name at all -
    /// and a match on a key's prefix would be the mechanical rename `CLAUDE.md` warns about.
    /// </summary>
    private static IEnumerable<Group> Templates(ResourceDictionary resources, Limits limits)
    {
        foreach (var dictionary in resources.MergedDictionaries)
        {
            var source = dictionary.Source?.OriginalString;

            if (source is not null && !source.Contains(Ours, StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            if (dictionary.Contains(SheetRowTemplate))
            {
                continue;
            }

            var file = source is null ? "read from disk" : System.IO.Path.GetFileName(source);

            var entries = new List<Entry>();

            foreach (var key in dictionary.Keys)
            {
                if (key is not string named || dictionary[key] is not DataTemplate template)
                {
                    continue;
                }

                entries.Add(DescribeTemplate(named, template, limits));
            }

            if (entries.Count > 0)
            {
                yield return new Group(file + " - templates", entries.OrderBy(entry => entry.Key, StringComparer.Ordinal).ToArray());
            }
        }
    }

    /// <summary>
    /// One template, drawn over its ordinary specimen and its extreme one. Disabled, wrong and
    /// chosen are the host control's states, not the template's, so those three cells are a dash.
    /// </summary>
    private static Entry DescribeTemplate(string key, DataTemplate template, Limits limits)
    {
        const string Target = nameof(DataTemplate);

        if (TemplateSpecimens(key) is not { } specimens)
        {
            return new Entry(
                key, Target,
                Sample.None($"nothing here knows what data {key} draws"),
                Sample.None(string.Empty), Sample.None(string.Empty), Sample.None(string.Empty), Sample.None(string.Empty));
        }

        return new Entry(
            key,
            Target,
            Drawn(template, specimens.Normal, limits),
            Sample.None(NoSuchState),
            Sample.None(NoSuchState),
            Sample.None(NoSuchState),
            Drawn(template, specimens.Extreme, limits));
    }

    /// <summary>A template over a specimen, measured and checked for a pixel like any other sample.</summary>
    private static Sample Drawn(DataTemplate template, object specimen, Limits limits)
    {
        var presenter = new ContentPresenter { Content = specimen, ContentTemplate = template };

        return Sized(presenter, limits);
    }
}
