<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Bws.Core\Bws.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <PropertyGroup>
    <!-- Windows shows this as the file description, in properties and in Task Manager. -->
    <AssemblyTitle>Better Windows Services</AssemblyTitle>
  </PropertyGroup>

</Project>